# Generated by Django 2.1 on 2021-11-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWBDataApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('colour', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
    ]
