# Generated by Django 2.1 on 2021-12-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWBDataApp', '0002_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batchcost',
            fields=[
                ('batchname', models.CharField(db_column='BatchName', max_length=15, primary_key=True, serialize=False)),
                ('batchdate', models.DateField(blank=True, db_column='BatchDate', null=True)),
                ('totalcost', models.DecimalField(db_column='TotalCost', decimal_places=2, max_digits=10)),
                ('totalweight', models.SmallIntegerField(db_column='TotalWeight')),
                ('priceperpound', models.DecimalField(db_column='PricePerPound', decimal_places=2, max_digits=10)),
                ('material1', models.CharField(blank=True, db_column='Material1', max_length=30, null=True)),
                ('weight1', models.SmallIntegerField(blank=True, db_column='Weight1', null=True)),
                ('value1', models.DecimalField(blank=True, db_column='Value1', decimal_places=2, max_digits=10, null=True)),
                ('material2', models.CharField(blank=True, db_column='Material2', max_length=30, null=True)),
                ('weight2', models.SmallIntegerField(blank=True, db_column='Weight2', null=True)),
                ('value2', models.DecimalField(blank=True, db_column='Value2', decimal_places=2, max_digits=10, null=True)),
                ('material3', models.CharField(blank=True, db_column='Material3', max_length=30, null=True)),
                ('weight3', models.SmallIntegerField(blank=True, db_column='Weight3', null=True)),
                ('value3', models.DecimalField(blank=True, db_column='Value3', decimal_places=2, max_digits=10, null=True)),
                ('material4', models.CharField(blank=True, db_column='Material4', max_length=30, null=True)),
                ('weight4', models.SmallIntegerField(blank=True, db_column='Weight4', null=True)),
                ('value4', models.DecimalField(blank=True, db_column='Value4', decimal_places=2, max_digits=10, null=True)),
                ('material5', models.CharField(blank=True, db_column='Material5', max_length=30, null=True)),
                ('weight5', models.SmallIntegerField(blank=True, db_column='Weight5', null=True)),
                ('value5', models.DecimalField(blank=True, db_column='Value5', decimal_places=2, max_digits=10, null=True)),
                ('material6', models.CharField(blank=True, db_column='Material6', max_length=30, null=True)),
                ('weight6', models.SmallIntegerField(blank=True, db_column='Weight6', null=True)),
                ('value6', models.DecimalField(blank=True, db_column='Value6', decimal_places=2, max_digits=10, null=True)),
                ('material7', models.CharField(blank=True, db_column='Material7', max_length=30, null=True)),
                ('weight7', models.SmallIntegerField(blank=True, db_column='Weight7', null=True)),
                ('value7', models.DecimalField(blank=True, db_column='Value7', decimal_places=2, max_digits=10, null=True)),
                ('material8', models.CharField(blank=True, db_column='Material8', max_length=30, null=True)),
                ('weight8', models.SmallIntegerField(blank=True, db_column='Weight8', null=True)),
                ('value8', models.DecimalField(blank=True, db_column='Value8', decimal_places=2, max_digits=10, null=True)),
                ('material9', models.CharField(blank=True, db_column='Material9', max_length=30, null=True)),
                ('weight9', models.SmallIntegerField(blank=True, db_column='Weight9', null=True)),
                ('value9', models.DecimalField(blank=True, db_column='Value9', decimal_places=2, max_digits=10, null=True)),
                ('material10', models.CharField(blank=True, db_column='Material10', max_length=30, null=True)),
                ('weight10', models.SmallIntegerField(blank=True, db_column='Weight10', null=True)),
                ('value10', models.DecimalField(blank=True, db_column='Value10', decimal_places=2, max_digits=10, null=True)),
                ('colour', models.CharField(blank=True, db_column='Colour', max_length=20, null=True)),
                ('colourweight', models.DecimalField(blank=True, db_column='ColourWeight', decimal_places=2, max_digits=10, null=True)),
                ('colourvalue', models.DecimalField(blank=True, db_column='ColourValue', decimal_places=2, max_digits=10, null=True)),
                ('foamweight', models.DecimalField(blank=True, db_column='FoamWeight', decimal_places=2, max_digits=10, null=True)),
                ('foamvalue', models.DecimalField(blank=True, db_column='FoamValue', decimal_places=2, max_digits=10, null=True)),
                ('totalshredweight', models.SmallIntegerField(blank=True, db_column='TotalShredWeight', null=True)),
            ],
            options={
                'db_table': 'BatchCost',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employeename', models.CharField(db_column='EmployeeName', max_length=40, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Employees',
                'managed': False,
            },
        ),
    ]
