# Generated by Django 2.1 on 2021-12-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWBDataApp', '0003_batchcost_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profileaverages',
            fields=[
                ('productname', models.CharField(db_column='ProductName', max_length=40, primary_key=True, serialize=False)),
                ('averageskidsperday', models.DecimalField(blank=True, db_column='AverageSkidsPerDay', decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'ProfileAverages',
                'managed': False,
            },
        ),
    ]
