# Generated by Django 2.1 on 2022-02-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWBDataApp', '0004_profileaverages'),
    ]

    operations = [
        migrations.AddField(
            model_name='colour',
            name='priceperpound',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
