# Generated by Django 2.1 on 2022-03-16 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWBDataApp', '0005_colour_priceperpound'),
    ]

    operations = [
        migrations.CreateModel(
            name='picsum',
            fields=[
                ('title', models.CharField(default='Test', max_length=40, primary_key=True, serialize=False)),
                ('testdate', models.DateField(default=datetime.date.today)),
                ('machineoperator', models.CharField(max_length=40, null=True)),
                ('temp1', models.BooleanField(default=False)),
                ('mixer', models.CharField(max_length=40, null=True)),
                ('temp2', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='PicAndSum/%Y/%m')),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
