# Generated by Django 2.1 on 2022-06-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWBDataApp', '0008_cisemailsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='picsum',
            name='numberoftests',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
